Uses clis from cli submodule (#26)
Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

diff --git a/scripts/kill-kube-ns b/scripts/kill-kube-ns
--- a/scripts/kill-kube-ns
+++ b/scripts/kill-kube-ns
@@ -20,26 +20,33 @@ if [ -z "$1" ]; then
     exit
 fi
 
+JQ=$(command -v "${BIN_DIR}/jq" || command -v jq)
+KUBECTL=$(command -v "${BIN_DIR}/kubectl" || command -v kubectl)
+
 set -eo pipefail
 
 die() { echo "$*" 1>&2 ; exit 1; }
 
 need() {
-	which "$1" &>/dev/null || die "Binary '$1' is missing but required"
+	command -v "$1" &>/dev/null || die "Binary '$1' is missing but required"
 }
 
 # checking pre-reqs
-
-need "jq"
 need "curl"
-need "kubectl"
+
+if [[ -z "${JQ}" ]]; then
+  die "jq is missing but required"
+fi
+if [[ -z "${KUBECTL}" ]]; then
+  die "kubectl is missing but required"
+fi
 
 PROJECT="$1"
 shift
 
 test -n "$PROJECT" || die "Missing arguments: kill-ns <namespace>"
 
-kubectl proxy &>/dev/null &
+${KUBECTL} proxy &>/dev/null &
 PROXY_PID=$!
 killproxy () {
 	kill $PROXY_PID
@@ -48,6 +55,6 @@ trap killproxy EXIT
 
 sleep 1 # give the proxy a second
 
-kubectl get namespace "$PROJECT" -o json | jq 'del(.spec.finalizers[] | select("kubernetes"))' | curl -s -k -H "Content-Type: application/json" -X PUT -o /dev/null --data-binary @- http://localhost:8001/api/v1/namespaces/$PROJECT/finalize && echo "Killed namespace: $PROJECT"
+${KUBECTL} get namespace "$PROJECT" -o json | ${JQ} 'del(.spec.finalizers[] | select("kubernetes"))' | curl -s -k -H "Content-Type: application/json" -X PUT -o /dev/null --data-binary @- http://localhost:8001/api/v1/namespaces/$PROJECT/finalize && echo "Killed namespace: $PROJECT"
 
 # proxy will get killed by the trap
